### ISSUE TITLE
Unhandled Exception: type 'Importance' is not a subtype of type 'Importance' where

### ISSUE THREAD

**Issue by sabarinathancs** [samuelezedi/locally#1]
Unhandled Exception: type 'Importance' is not a subtype of type 'Importance' where

**Comment by samuelezedi** [comment]
currently working on this. just give me a few hours

**Comment by samuelezedi** [comment]
> Unhandled Exception: type 'Importance' is not a subtype of type 'Importance' where

can I see your code please?

**Comment by sabarinathancs** [comment]
ya sure

**Comment by brasizza** [comment]
Same here

    Locally locally;
                          String title = "AAA";
                          String message = "AAA";
      locally = Locally(
          context: context,
          payload: 'test',
          pageRoute: MaterialPageRoute(builder: (context) => SecondScreen(title: title, message:  message)),
          appIcon: 'mipmap/ic_launcher',
      );
      locally.show(title: title, message: message);


/flutter ( 5976): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: type 'Importance' is not a subtype of type 'Importance' where
E/flutter ( 5976):   Importance is from package:locally/src/helpers.dart
E/flutter ( 5976):   Importance is from package:flutter_local_notifications/src/platform_specifics/android/enums.dart

**Comment by samuelezedi** [comment]
This issue has been fixed. Update the package to a newer version. 

`locally: ^0.2.6+7`

**Comment by brasizza** [comment]
> This issue has been fixed. Update the package to a newer version.
> 
> `locally: ^0.2.6+7`

Very nice broooo thanks!!
Worked just awesome

**Comment by samuelezedi** [comment]
> > This issue has been fixed. Update the package to a newer version.
> > `locally: ^0.2.6+7`
> 
> Very nice broooo thanks!!
> Worked just awesome

You're welcome, anytime
