### ISSUE TITLE
Example of how set time

### ISSUE THREAD

**Issue by johnareid54** [samuelezedi/locally#9]
I like this package, it makes notifications a lot easier!

I am having a problem getting the following to work

`locally.showDailyAtTime(title: title.text, message: message.text, time: Time.hour);`

Could you show an example say time equals 9:00 in the morning?

Thanks

**Comment by ntatko** [comment]
So, I'm running into that issue, too, but if you look here, you can see the types that he's using: https://github.com/samuelezedi/locally/blob/master/lib/src/helpers.dart

**Comment by allasca** [comment]
integer? how? still don't get it

**Comment by khaniat** [comment]
> So, I'm running into that issue, too, but if you look here, you can see the types that he's using: https://github.com/samuelezedi/locally/blob/master/lib/src/helpers.dart

Did you manage to fix it?

**Comment by johnareid54** [comment]
@khaniat Did you manage to fix it?

Regret to say I got sidetracked and started to rewrite the app from the beginning.

**Comment by johnareid54** [comment]
Occasionally I get a new reply asking if I have fix this problem.

Finally I got around to looking at it and it is not an easy fix as it requires timezone and latest packages.

However after some time on the web I came across this - it is easy to setup and will schedule the notifications.

https://blog.logrocket.com/implementing-local-notifications-in-flutter/
